apiVersion: v1
kind: Service
metadata:
  name: {{ include "compose-frontend.fullname" . }}
  labels:
    {{- include "compose-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # targetPort: http
      # protocol: TCP
      # name: http
  selector:
    {{- include "compose-frontend.selectorLabels" . | nindent 4 }}
